
import image1 from "/image1.jpg";
import image2 from "/image2.jpg";
import image3 from "/image3.jpg";
import image4 from "/image4.jpg";
import image5 from "/image5.jpg";
import image6 from "/image6.jpg";
import image7 from "/image7.jpg";
import image8 from "/image8.jpg";
import image9 from "/image9.jpg";
import image10 from "/image10.jpg";
import image11 from "/image11.jpg";
import image12 from "/image12.jpg";
import image13 from "/image13.jpg";
import { GiMailShirt } from "react-icons/gi";


const properties = [
    {
        id: 1,
        name: "Property 1",
        description: "Stylish houses and homes with spacious parking and no noises around.",
        price: "105,000",
        images: [image1],
        Images:[image11, image1, image12, image2],
        location: "Location 1",
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1500,
        type: "House",
        title: "Property 1 Title",
        agentEmail: "realestate@gmail.com",
        agentPhone: "0712345678",
    },
      {
        id: 2,
        name: "Property 2",
        description: "Stylish houses with neighbors around.",
        price: "110,000",
        images: [image2],
        Images:[image11, image10, image12, image2],
        location: "Location 2",
        bedrooms: 5,
        bathrooms: 1,
        sqft: 1500,
        type: "House",
        title: "Property 2 Title",
        agentEmail: "realestate@gmail.com",
        agentPhone: "0712345678",
    },
          {
        id: 3,
        name: "Property 3",
        description: "Affordable homes with spacious parking, garden and security.",
        price: "135,000",
        images: [image3],
        Images:[image13, image9, image1, image3],
        location: "Location 3",
        bedrooms: 5,
        bathrooms: 2,
        sqft: 1500,
        type: "House",
        title: "Property 3 Title",
        agentEmail: "realestate@gmail.com",
        agentPhone: "0712345678",
    },
              {
        id: 4,
        name: "Property 4",
        description: "Stylish and standard houses with small farming gardens.",
        price: "150,000",
        images: [image4],
        Images:[image2, image6, image7, image4],
        location: "Location 4",
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1500,
        type: "House",
        title: "Property 1 Title",
        agentEmail: "realestate@gmail.com",
        agentPhone: "0712345678",
    },
               {
        id: 1,
        name: "Property 1",
        description: "Stylish houses and homes with neighbors waiting for you.",
        price: "105,000",
        images: [image5],
        Images:[image11, image7, image4, image2],
        location: "Location 1",
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1500,
        type: "House",
        title: "Property 1 Title",
        agentEmail: "realestate@gmail.com",
        agentPhone: "0712345678",
    },
      {
        id: 2,
        name: "Property 2",
        description: "Stylish houses and homes with ample parking.",
        price: "110,000",
        images: [image6],
        Images:[image11, image6, image12, image2],
        location: "Location 2",
        bedrooms: 5,
        bathrooms: 1,
        sqft: 1500,
        type: "House",
        title: "Property 2 Title",
        agentEmail: "realestate@gmail.com",
        agentPhone: "0712345678",
    },
          {
        id: 3,
        name: "Property 3",
        description: "Stylish houses and homes with spacious field.",
        price: "135,000",
        images: [image7],
        Images:[image11, image10, image12, image2],
        location: "Location 3",
        bedrooms: 5,
        bathrooms: 2,
        sqft: 1500,
        type: "House",
        title: "Property 3 Title",
        agentEmail: "realestate@gmail.com",
        agentPhone: "0712345678",
    },
              {
        id: 4,
        name: "Property 4",
        description: "Stylish houses and homes with spacious parking and no noises around.",
        price: "150,000",
        images: [image8],
        Images:[image11, image8, image13, image2],
        location: "Location 4",
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1500,
        type: "House",
        title: "Property 1 Title",
        agentEmail: "realestate@gmail.com",
        agentPhone: "0712345678",
    },
                {
        id: 4,
        name: "Property 4",
        description: "Stylish homes with spacious parking and no noises around.",
        price: "150,000",
        images: [image9],
        Images:[image11, image10, image12, image2],
        location: "Location 4",
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1500,
        type: "House",
        title: "Property 1 Title",
        agentEmail: "realestate@gmail.com",
        agentPhone: "0712345678",
    },
]

export default properties;